/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/rerank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rerank */
        post: operations["rerank_rerank_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CandidateRationale */
        CandidateRationale: {
            /** Agentid */
            agentId: string;
            /** Reason */
            reason: string;
        };
        /**
         * CandidateSignals
         * @description Mirrors `apps/api`'s `ReputationSignalsInput` (the flat wire shape,
         *     not the full digest with sampleSize — Go's own wire contract already
         *     established this flattened shape, and Python receives the same one).
         *     Every field is `None` when that signal is genuinely missing (F-1309) —
         *     never a fabricated 0.
         */
        CandidateSignals: {
            /** Communication */
            communication?: number | null;
            /** Completionrate */
            completionRate?: number | null;
            /** Disputesignal */
            disputeSignal?: number | null;
            /** Historicalscale */
            historicalScale?: number | null;
            /** Qualityfeedback */
            qualityFeedback?: number | null;
        };
        /** CandidateSnapshot */
        CandidateSnapshot: {
            /** Agentid */
            agentId: string;
            /** Semanticsimilarity */
            semanticSimilarity?: number | null;
            signals?: components["schemas"]["CandidateSignals"] | null;
            /** V0Score */
            v0Score: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RerankRequest */
        RerankRequest: {
            /** Candidates */
            candidates: components["schemas"]["CandidateSnapshot"][];
            /**
             * Stage
             * @enum {string}
             */
            stage: "SHADOW" | "GRADUAL" | "PRIMARY";
            /** Taskdescription */
            taskDescription: string;
        };
        /**
         * RerankResponse
         * @description `rerank_service_version`/`ranking_policy_version` are two
         *     INDEPENDENT fields (F-1922) — never merged into one version string.
         *     `ranking_policy_version` is nullable: this skeleton (T-1910/T-1911)
         *     runs with no registered `ctr_models` row yet, matching design.md's own
         *     note that an early-stage reranker can run with "未版本化的
         *     prompt/权重".
         */
        RerankResponse: {
            /** Llmadopted */
            llmAdopted: boolean;
            /** Rankedagentids */
            rankedAgentIds: string[];
            /** Rankingpolicyversion */
            rankingPolicyVersion?: string | null;
            /** Rationales */
            rationales: components["schemas"]["CandidateRationale"][];
            /** Rerankserviceversion */
            rerankServiceVersion: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    rerank_rerank_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RerankRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RerankResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
